Adding #include <string> for windows build
compilation failed in MSVC with
jsonnet\third_party\md5\md5.cpp(353): warning C4717: 'operator<<': recursive on all control paths, function will cause runtime stack overflow
because
std::ostream& operator<<(std::ostream&, std::string)
was not defined, so it implicitly converted the hex digest back to MD5